### ISSUE TITLE
1 view but showing another to right

### ISSUE THREAD

**Issue by billy9222** [astrit-veliu/Smoolider#1]
so the scenaio is 

I have 2 elements in the smooth slider if I remove one and notify the adapter.

it changes the element to 1 but it still has a view visible to its right which feels there is still a view there.

but if I go with just 1 element then it doesn't draw any view.

can you please tell how should i fix it

**Comment by astrit-veliu** [comment]
Hi @billy9222 , it looks like the view is not invalidating properly, i will take a look to it :) Sorry for my late reply, best regards!

**Comment by astrit-veliu** [comment]
@billy9222 issue fixed with the latest commit/release. Add/Remove items is way more easier now by the predefined methods, next update will contain a more detailed documentation and optimising further the lib. Thank you for reporting!
